config/routes.rb
Rails.application.routes.draw do

  resources :user_projects
  resources :artifacts
  resources :tenants do
    resources :projects do
      get 'users', on: :member 
      put 'add_user', on: :member 
    end
  end
  resources :members
  get 'home/index'

   root :to => "home#index"

    
  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do   
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  # devise_for :users, :controllers => { 
  #   :registrations => "registrations",
  #   :confirmations => "confirmations",
  #   :sessions => "milia/sessions", 
  #   :passwords => "milia/passwords", 
  # }
  
  devise_for :users, :controllers => { 
    :registrations => "milia/registrations",
    :confirmations => "milia/confirmations",
    :sessions => "milia/sessions", 
    :passwords => "milia/passwords",   
  }
  
  match '/plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match '/plan/update' => 'tenants#update', via: [:put, :patch], as: :update_plan
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse" aria-expanded="false" aria-controls="navbar">
      <!--<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">-->
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to ("<i class='fa fa-file'></i> " +'ProductionRequest').html_safe, root_path, class: "navbar-brand" %>
    </div>
      
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= truncate(current_user.email, length: 25) %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <!--<li><= link_to "Dashboard", dashboard_path %></li>-->
            <!--<li><= link_to "List A Space", new_venue_path %></li>-->
            <!--<li><= link_to "Past Spaces", past_spaces_path %></li>-->
            <!--<li><= link_to "Reservations", your_reservations_path %></li>-->
            <% if current_user && current_user.is_admin? %>
              <li><%= link_to "<i class='fa fa-users'></i> Add Members".html_safe, new_member_path %></li>
              <li><%= link_to "<i class='fa fa-briefcase'></i> Change Plan".html_safe, edit_plan_path %></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
      <!--<ul class="nav navbar-right col-md-4">-->
          
      <!--</ul>-->
    </div>
  </div>
</nav>